/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Exchange Simulator Docs
 * API Docs
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-instance';
export interface OrderRequestDto {
  userId?: number;
  token?: string;
  limit?: number;
  quantity?: number;
}

export type OrderResponseDtoTransactionType = typeof OrderResponseDtoTransactionType[keyof typeof OrderResponseDtoTransactionType];


export const OrderResponseDtoTransactionType = {
  BUY: 'BUY',
  SELL: 'SELL',
} as const;

export type OrderResponseDtoOrderType = typeof OrderResponseDtoOrderType[keyof typeof OrderResponseDtoOrderType];


export const OrderResponseDtoOrderType = {
  LIMIT: 'LIMIT',
  MARKET: 'MARKET',
} as const;

export interface OrderResponseDto {
  userId?: number;
  orderId?: number;
  createdAt?: string;
  token?: string;
  quantity?: number;
  entry?: number;
  orderValue?: number;
  transactionType?: OrderResponseDtoTransactionType;
  orderType?: OrderResponseDtoOrderType;
  closedAt?: string;
}

export interface UserCreateRequestDto {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  email: string;
  password?: string;
  role?: string;
}

export interface UserResponseDto {
  id?: number;
  updatedAt?: string;
  createdAt?: string;
  username?: string;
  email?: string;
  funds?: number;
}

export interface LoginRequestDto {
  username?: string;
  password?: string;
}

export interface SpotPositionResponseDto {
  positionId?: number;
  token?: string;
  quantity?: number;
  avgBuyPrice?: number;
  positionValue?: number;
  timestamp?: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getUserSellOrdersResponse200 = {
  data: Blob
  status: 200
}
    
export type getUserSellOrdersResponseSuccess = (getUserSellOrdersResponse200) & {
  headers: Headers;
};
;

export type getUserSellOrdersResponse = (getUserSellOrdersResponseSuccess)

export const getGetUserSellOrdersUrl = () => {


  

  return `/api/users-orders/market/sell`
}

export const getUserSellOrders = async ( options?: RequestInit): Promise<getUserSellOrdersResponse> => {
  
  return customInstance<getUserSellOrdersResponse>(getGetUserSellOrdersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserSellOrdersQueryKey = () => {
    return [
    `/api/users-orders/market/sell`
    ] as const;
    }

    
export const getGetUserSellOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getUserSellOrders>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserSellOrdersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserSellOrders>>> = ({ signal }) => getUserSellOrders({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserSellOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getUserSellOrders>>>
export type GetUserSellOrdersQueryError = unknown


export function useGetUserSellOrders<TData = Awaited<ReturnType<typeof getUserSellOrders>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSellOrders>>,
          TError,
          Awaited<ReturnType<typeof getUserSellOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSellOrders<TData = Awaited<ReturnType<typeof getUserSellOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSellOrders>>,
          TError,
          Awaited<ReturnType<typeof getUserSellOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSellOrders<TData = Awaited<ReturnType<typeof getUserSellOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserSellOrders<TData = Awaited<ReturnType<typeof getUserSellOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserSellOrdersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type sellResponse200 = {
  data: Blob
  status: 200
}
    
export type sellResponseSuccess = (sellResponse200) & {
  headers: Headers;
};
;

export type sellResponse = (sellResponseSuccess)

export const getSellUrl = () => {


  

  return `/api/users-orders/market/sell`
}

export const sell = async (orderRequestDto: OrderRequestDto, options?: RequestInit): Promise<sellResponse> => {
  
  return customInstance<sellResponse>(getSellUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      orderRequestDto,)
  }
);}




export const getSellMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sell>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sell>>, TError,{data: OrderRequestDto}, TContext> => {

const mutationKey = ['sell'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sell>>, {data: OrderRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  sell(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SellMutationResult = NonNullable<Awaited<ReturnType<typeof sell>>>
    export type SellMutationBody = OrderRequestDto
    export type SellMutationError = unknown

    export const useSell = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sell>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sell>>,
        TError,
        {data: OrderRequestDto},
        TContext
      > => {
      return useMutation(getSellMutationOptions(options), queryClient);
    }
    
export type getUserBuyOrdersResponse200 = {
  data: Blob
  status: 200
}
    
export type getUserBuyOrdersResponseSuccess = (getUserBuyOrdersResponse200) & {
  headers: Headers;
};
;

export type getUserBuyOrdersResponse = (getUserBuyOrdersResponseSuccess)

export const getGetUserBuyOrdersUrl = () => {


  

  return `/api/users-orders/market/buy`
}

export const getUserBuyOrders = async ( options?: RequestInit): Promise<getUserBuyOrdersResponse> => {
  
  return customInstance<getUserBuyOrdersResponse>(getGetUserBuyOrdersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserBuyOrdersQueryKey = () => {
    return [
    `/api/users-orders/market/buy`
    ] as const;
    }

    
export const getGetUserBuyOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getUserBuyOrders>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserBuyOrdersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBuyOrders>>> = ({ signal }) => getUserBuyOrders({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserBuyOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getUserBuyOrders>>>
export type GetUserBuyOrdersQueryError = unknown


export function useGetUserBuyOrders<TData = Awaited<ReturnType<typeof getUserBuyOrders>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBuyOrders>>,
          TError,
          Awaited<ReturnType<typeof getUserBuyOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBuyOrders<TData = Awaited<ReturnType<typeof getUserBuyOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBuyOrders>>,
          TError,
          Awaited<ReturnType<typeof getUserBuyOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBuyOrders<TData = Awaited<ReturnType<typeof getUserBuyOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserBuyOrders<TData = Awaited<ReturnType<typeof getUserBuyOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserBuyOrdersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type buyResponse200 = {
  data: Blob
  status: 200
}
    
export type buyResponseSuccess = (buyResponse200) & {
  headers: Headers;
};
;

export type buyResponse = (buyResponseSuccess)

export const getBuyUrl = () => {


  

  return `/api/users-orders/market/buy`
}

export const buy = async (orderRequestDto: OrderRequestDto, options?: RequestInit): Promise<buyResponse> => {
  
  return customInstance<buyResponse>(getBuyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      orderRequestDto,)
  }
);}




export const getBuyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof buy>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof buy>>, TError,{data: OrderRequestDto}, TContext> => {

const mutationKey = ['buy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof buy>>, {data: OrderRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  buy(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BuyMutationResult = NonNullable<Awaited<ReturnType<typeof buy>>>
    export type BuyMutationBody = OrderRequestDto
    export type BuyMutationError = unknown

    export const useBuy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof buy>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof buy>>,
        TError,
        {data: OrderRequestDto},
        TContext
      > => {
      return useMutation(getBuyMutationOptions(options), queryClient);
    }
    
export type getUserSellOrders1Response200 = {
  data: Blob
  status: 200
}
    
export type getUserSellOrders1ResponseSuccess = (getUserSellOrders1Response200) & {
  headers: Headers;
};
;

export type getUserSellOrders1Response = (getUserSellOrders1ResponseSuccess)

export const getGetUserSellOrders1Url = () => {


  

  return `/api/users-orders/limit/sell`
}

export const getUserSellOrders1 = async ( options?: RequestInit): Promise<getUserSellOrders1Response> => {
  
  return customInstance<getUserSellOrders1Response>(getGetUserSellOrders1Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserSellOrders1QueryKey = () => {
    return [
    `/api/users-orders/limit/sell`
    ] as const;
    }

    
export const getGetUserSellOrders1QueryOptions = <TData = Awaited<ReturnType<typeof getUserSellOrders1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserSellOrders1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserSellOrders1>>> = ({ signal }) => getUserSellOrders1({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserSellOrders1QueryResult = NonNullable<Awaited<ReturnType<typeof getUserSellOrders1>>>
export type GetUserSellOrders1QueryError = unknown


export function useGetUserSellOrders1<TData = Awaited<ReturnType<typeof getUserSellOrders1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSellOrders1>>,
          TError,
          Awaited<ReturnType<typeof getUserSellOrders1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSellOrders1<TData = Awaited<ReturnType<typeof getUserSellOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSellOrders1>>,
          TError,
          Awaited<ReturnType<typeof getUserSellOrders1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSellOrders1<TData = Awaited<ReturnType<typeof getUserSellOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserSellOrders1<TData = Awaited<ReturnType<typeof getUserSellOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserSellOrders1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type sell1Response200 = {
  data: Blob
  status: 200
}
    
export type sell1ResponseSuccess = (sell1Response200) & {
  headers: Headers;
};
;

export type sell1Response = (sell1ResponseSuccess)

export const getSell1Url = () => {


  

  return `/api/users-orders/limit/sell`
}

export const sell1 = async (orderRequestDto: OrderRequestDto, options?: RequestInit): Promise<sell1Response> => {
  
  return customInstance<sell1Response>(getSell1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      orderRequestDto,)
  }
);}




export const getSell1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sell1>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sell1>>, TError,{data: OrderRequestDto}, TContext> => {

const mutationKey = ['sell1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sell1>>, {data: OrderRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  sell1(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type Sell1MutationResult = NonNullable<Awaited<ReturnType<typeof sell1>>>
    export type Sell1MutationBody = OrderRequestDto
    export type Sell1MutationError = unknown

    export const useSell1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sell1>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sell1>>,
        TError,
        {data: OrderRequestDto},
        TContext
      > => {
      return useMutation(getSell1MutationOptions(options), queryClient);
    }
    
export type getUserBuyOrders1Response200 = {
  data: Blob
  status: 200
}
    
export type getUserBuyOrders1ResponseSuccess = (getUserBuyOrders1Response200) & {
  headers: Headers;
};
;

export type getUserBuyOrders1Response = (getUserBuyOrders1ResponseSuccess)

export const getGetUserBuyOrders1Url = () => {


  

  return `/api/users-orders/limit/buy`
}

export const getUserBuyOrders1 = async ( options?: RequestInit): Promise<getUserBuyOrders1Response> => {
  
  return customInstance<getUserBuyOrders1Response>(getGetUserBuyOrders1Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserBuyOrders1QueryKey = () => {
    return [
    `/api/users-orders/limit/buy`
    ] as const;
    }

    
export const getGetUserBuyOrders1QueryOptions = <TData = Awaited<ReturnType<typeof getUserBuyOrders1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserBuyOrders1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBuyOrders1>>> = ({ signal }) => getUserBuyOrders1({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserBuyOrders1QueryResult = NonNullable<Awaited<ReturnType<typeof getUserBuyOrders1>>>
export type GetUserBuyOrders1QueryError = unknown


export function useGetUserBuyOrders1<TData = Awaited<ReturnType<typeof getUserBuyOrders1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBuyOrders1>>,
          TError,
          Awaited<ReturnType<typeof getUserBuyOrders1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBuyOrders1<TData = Awaited<ReturnType<typeof getUserBuyOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBuyOrders1>>,
          TError,
          Awaited<ReturnType<typeof getUserBuyOrders1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBuyOrders1<TData = Awaited<ReturnType<typeof getUserBuyOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserBuyOrders1<TData = Awaited<ReturnType<typeof getUserBuyOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserBuyOrders1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type buy1Response200 = {
  data: Blob
  status: 200
}
    
export type buy1ResponseSuccess = (buy1Response200) & {
  headers: Headers;
};
;

export type buy1Response = (buy1ResponseSuccess)

export const getBuy1Url = () => {


  

  return `/api/users-orders/limit/buy`
}

export const buy1 = async (orderRequestDto: OrderRequestDto, options?: RequestInit): Promise<buy1Response> => {
  
  return customInstance<buy1Response>(getBuy1Url(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      orderRequestDto,)
  }
);}




export const getBuy1MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof buy1>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof buy1>>, TError,{data: OrderRequestDto}, TContext> => {

const mutationKey = ['buy1'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof buy1>>, {data: OrderRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  buy1(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type Buy1MutationResult = NonNullable<Awaited<ReturnType<typeof buy1>>>
    export type Buy1MutationBody = OrderRequestDto
    export type Buy1MutationError = unknown

    export const useBuy1 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof buy1>>, TError,{data: OrderRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof buy1>>,
        TError,
        {data: OrderRequestDto},
        TContext
      > => {
      return useMutation(getBuy1MutationOptions(options), queryClient);
    }
    
export type createUserResponse200 = {
  data: Blob
  status: 200
}
    
export type createUserResponseSuccess = (createUserResponse200) & {
  headers: Headers;
};
;

export type createUserResponse = (createUserResponseSuccess)

export const getCreateUserUrl = () => {


  

  return `/api/auth/registration`
}

export const createUser = async (userCreateRequestDto: UserCreateRequestDto, options?: RequestInit): Promise<createUserResponse> => {
  
  return customInstance<createUserResponse>(getCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userCreateRequestDto,)
  }
);}




export const getCreateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: UserCreateRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: UserCreateRequestDto}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: UserCreateRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = UserCreateRequestDto
    export type CreateUserMutationError = unknown

    export const useCreateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: UserCreateRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: UserCreateRequestDto},
        TContext
      > => {
      return useMutation(getCreateUserMutationOptions(options), queryClient);
    }
    
export type logoutResponse200 = {
  data: Blob
  status: 200
}
    
export type logoutResponseSuccess = (logoutResponse200) & {
  headers: Headers;
};
;

export type logoutResponse = (logoutResponseSuccess)

export const getLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {
  
  return customInstance<logoutResponse>(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = unknown

    export const useLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options), queryClient);
    }
    
export type authUserResponse200 = {
  data: Blob
  status: 200
}
    
export type authUserResponseSuccess = (authUserResponse200) & {
  headers: Headers;
};
;

export type authUserResponse = (authUserResponseSuccess)

export const getAuthUserUrl = () => {


  

  return `/api/auth/login`
}

export const authUser = async (loginRequestDto: LoginRequestDto, options?: RequestInit): Promise<authUserResponse> => {
  
  return customInstance<authUserResponse>(getAuthUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequestDto,)
  }
);}




export const getAuthUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authUser>>, TError,{data: LoginRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authUser>>, TError,{data: LoginRequestDto}, TContext> => {

const mutationKey = ['authUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authUser>>, {data: LoginRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  authUser(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AuthUserMutationResult = NonNullable<Awaited<ReturnType<typeof authUser>>>
    export type AuthUserMutationBody = LoginRequestDto
    export type AuthUserMutationError = unknown

    export const useAuthUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authUser>>, TError,{data: LoginRequestDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authUser>>,
        TError,
        {data: LoginRequestDto},
        TContext
      > => {
      return useMutation(getAuthUserMutationOptions(options), queryClient);
    }
    
export type getUsersResponse200 = {
  data: Blob
  status: 200
}
    
export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
;

export type getUsersResponse = (getUsersResponseSuccess)

export const getGetUsersUrl = () => {


  

  return `/api/users`
}

export const getUsers = async ( options?: RequestInit): Promise<getUsersResponse> => {
  
  return customInstance<getUsersResponse>(getGetUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUsersQueryKey = () => {
    return [
    `/api/users`
    ] as const;
    }

    
export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = unknown


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getUserResponse200 = {
  data: Blob
  status: 200
}
    
export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
;

export type getUserResponse = (getUserResponseSuccess)

export const getGetUserUrl = (id: number,) => {


  

  return `/api/users/${id}`
}

export const getUser = async (id: number, options?: RequestInit): Promise<getUserResponse> => {
  
  return customInstance<getUserResponse>(getGetUserUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserQueryKey = (id: number,) => {
    return [
    `/api/users/${id}`
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = unknown


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getMeResponse200 = {
  data: Blob
  status: 200
}
    
export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
;

export type getMeResponse = (getMeResponseSuccess)

export const getGetMeUrl = () => {


  

  return `/api/users/me`
}

export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {
  
  return customInstance<getMeResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/users/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = unknown


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getPortfolioResponse200 = {
  data: Blob
  status: 200
}
    
export type getPortfolioResponseSuccess = (getPortfolioResponse200) & {
  headers: Headers;
};
;

export type getPortfolioResponse = (getPortfolioResponseSuccess)

export const getGetPortfolioUrl = () => {


  

  return `/api/users-positions`
}

export const getPortfolio = async ( options?: RequestInit): Promise<getPortfolioResponse> => {
  
  return customInstance<getPortfolioResponse>(getGetPortfolioUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPortfolioQueryKey = () => {
    return [
    `/api/users-positions`
    ] as const;
    }

    
export const getGetPortfolioQueryOptions = <TData = Awaited<ReturnType<typeof getPortfolio>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPortfolioQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPortfolio>>> = ({ signal }) => getPortfolio({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPortfolioQueryResult = NonNullable<Awaited<ReturnType<typeof getPortfolio>>>
export type GetPortfolioQueryError = unknown


export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPortfolio>>,
          TError,
          Awaited<ReturnType<typeof getPortfolio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPortfolio>>,
          TError,
          Awaited<ReturnType<typeof getPortfolio>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPortfolio<TData = Awaited<ReturnType<typeof getPortfolio>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPortfolio>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPortfolioQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getSpotPositionResponse200 = {
  data: Blob
  status: 200
}
    
export type getSpotPositionResponseSuccess = (getSpotPositionResponse200) & {
  headers: Headers;
};
;

export type getSpotPositionResponse = (getSpotPositionResponseSuccess)

export const getGetSpotPositionUrl = (token: string,) => {


  

  return `/api/users-positions/${token}`
}

export const getSpotPosition = async (token: string, options?: RequestInit): Promise<getSpotPositionResponse> => {
  
  return customInstance<getSpotPositionResponse>(getGetSpotPositionUrl(token),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSpotPositionQueryKey = (token: string,) => {
    return [
    `/api/users-positions/${token}`
    ] as const;
    }

    
export const getGetSpotPositionQueryOptions = <TData = Awaited<ReturnType<typeof getSpotPosition>>, TError = unknown>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpotPosition>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSpotPositionQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSpotPosition>>> = ({ signal }) => getSpotPosition(token, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSpotPosition>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSpotPositionQueryResult = NonNullable<Awaited<ReturnType<typeof getSpotPosition>>>
export type GetSpotPositionQueryError = unknown


export function useGetSpotPosition<TData = Awaited<ReturnType<typeof getSpotPosition>>, TError = unknown>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpotPosition>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpotPosition>>,
          TError,
          Awaited<ReturnType<typeof getSpotPosition>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpotPosition<TData = Awaited<ReturnType<typeof getSpotPosition>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpotPosition>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSpotPosition>>,
          TError,
          Awaited<ReturnType<typeof getSpotPosition>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSpotPosition<TData = Awaited<ReturnType<typeof getSpotPosition>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpotPosition>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSpotPosition<TData = Awaited<ReturnType<typeof getSpotPosition>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSpotPosition>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSpotPositionQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getUserOrdersResponse200 = {
  data: Blob
  status: 200
}
    
export type getUserOrdersResponseSuccess = (getUserOrdersResponse200) & {
  headers: Headers;
};
;

export type getUserOrdersResponse = (getUserOrdersResponseSuccess)

export const getGetUserOrdersUrl = () => {


  

  return `/api/users-orders`
}

export const getUserOrders = async ( options?: RequestInit): Promise<getUserOrdersResponse> => {
  
  return customInstance<getUserOrdersResponse>(getGetUserOrdersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserOrdersQueryKey = () => {
    return [
    `/api/users-orders`
    ] as const;
    }

    
export const getGetUserOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getUserOrders>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserOrdersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserOrders>>> = ({ signal }) => getUserOrders({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getUserOrders>>>
export type GetUserOrdersQueryError = unknown


export function useGetUserOrders<TData = Awaited<ReturnType<typeof getUserOrders>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserOrders>>,
          TError,
          Awaited<ReturnType<typeof getUserOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserOrders<TData = Awaited<ReturnType<typeof getUserOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserOrders>>,
          TError,
          Awaited<ReturnType<typeof getUserOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserOrders<TData = Awaited<ReturnType<typeof getUserOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserOrders<TData = Awaited<ReturnType<typeof getUserOrders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserOrdersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getUserSellOrders2Response200 = {
  data: Blob
  status: 200
}
    
export type getUserSellOrders2ResponseSuccess = (getUserSellOrders2Response200) & {
  headers: Headers;
};
;

export type getUserSellOrders2Response = (getUserSellOrders2ResponseSuccess)

export const getGetUserSellOrders2Url = () => {


  

  return `/api/users-orders/sell`
}

export const getUserSellOrders2 = async ( options?: RequestInit): Promise<getUserSellOrders2Response> => {
  
  return customInstance<getUserSellOrders2Response>(getGetUserSellOrders2Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserSellOrders2QueryKey = () => {
    return [
    `/api/users-orders/sell`
    ] as const;
    }

    
export const getGetUserSellOrders2QueryOptions = <TData = Awaited<ReturnType<typeof getUserSellOrders2>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserSellOrders2QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserSellOrders2>>> = ({ signal }) => getUserSellOrders2({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserSellOrders2QueryResult = NonNullable<Awaited<ReturnType<typeof getUserSellOrders2>>>
export type GetUserSellOrders2QueryError = unknown


export function useGetUserSellOrders2<TData = Awaited<ReturnType<typeof getUserSellOrders2>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSellOrders2>>,
          TError,
          Awaited<ReturnType<typeof getUserSellOrders2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSellOrders2<TData = Awaited<ReturnType<typeof getUserSellOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSellOrders2>>,
          TError,
          Awaited<ReturnType<typeof getUserSellOrders2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSellOrders2<TData = Awaited<ReturnType<typeof getUserSellOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserSellOrders2<TData = Awaited<ReturnType<typeof getUserSellOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSellOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserSellOrders2QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getUserOrders1Response200 = {
  data: Blob
  status: 200
}
    
export type getUserOrders1ResponseSuccess = (getUserOrders1Response200) & {
  headers: Headers;
};
;

export type getUserOrders1Response = (getUserOrders1ResponseSuccess)

export const getGetUserOrders1Url = () => {


  

  return `/api/users-orders/market`
}

export const getUserOrders1 = async ( options?: RequestInit): Promise<getUserOrders1Response> => {
  
  return customInstance<getUserOrders1Response>(getGetUserOrders1Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserOrders1QueryKey = () => {
    return [
    `/api/users-orders/market`
    ] as const;
    }

    
export const getGetUserOrders1QueryOptions = <TData = Awaited<ReturnType<typeof getUserOrders1>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserOrders1QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserOrders1>>> = ({ signal }) => getUserOrders1({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserOrders1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserOrders1QueryResult = NonNullable<Awaited<ReturnType<typeof getUserOrders1>>>
export type GetUserOrders1QueryError = unknown


export function useGetUserOrders1<TData = Awaited<ReturnType<typeof getUserOrders1>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserOrders1>>,
          TError,
          Awaited<ReturnType<typeof getUserOrders1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserOrders1<TData = Awaited<ReturnType<typeof getUserOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserOrders1>>,
          TError,
          Awaited<ReturnType<typeof getUserOrders1>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserOrders1<TData = Awaited<ReturnType<typeof getUserOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserOrders1<TData = Awaited<ReturnType<typeof getUserOrders1>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders1>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserOrders1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getUserOrders2Response200 = {
  data: Blob
  status: 200
}
    
export type getUserOrders2ResponseSuccess = (getUserOrders2Response200) & {
  headers: Headers;
};
;

export type getUserOrders2Response = (getUserOrders2ResponseSuccess)

export const getGetUserOrders2Url = () => {


  

  return `/api/users-orders/limit`
}

export const getUserOrders2 = async ( options?: RequestInit): Promise<getUserOrders2Response> => {
  
  return customInstance<getUserOrders2Response>(getGetUserOrders2Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserOrders2QueryKey = () => {
    return [
    `/api/users-orders/limit`
    ] as const;
    }

    
export const getGetUserOrders2QueryOptions = <TData = Awaited<ReturnType<typeof getUserOrders2>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserOrders2QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserOrders2>>> = ({ signal }) => getUserOrders2({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserOrders2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserOrders2QueryResult = NonNullable<Awaited<ReturnType<typeof getUserOrders2>>>
export type GetUserOrders2QueryError = unknown


export function useGetUserOrders2<TData = Awaited<ReturnType<typeof getUserOrders2>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserOrders2>>,
          TError,
          Awaited<ReturnType<typeof getUserOrders2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserOrders2<TData = Awaited<ReturnType<typeof getUserOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserOrders2>>,
          TError,
          Awaited<ReturnType<typeof getUserOrders2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserOrders2<TData = Awaited<ReturnType<typeof getUserOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserOrders2<TData = Awaited<ReturnType<typeof getUserOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserOrders2QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getUserBuyOrders2Response200 = {
  data: Blob
  status: 200
}
    
export type getUserBuyOrders2ResponseSuccess = (getUserBuyOrders2Response200) & {
  headers: Headers;
};
;

export type getUserBuyOrders2Response = (getUserBuyOrders2ResponseSuccess)

export const getGetUserBuyOrders2Url = () => {


  

  return `/api/users-orders/buy`
}

export const getUserBuyOrders2 = async ( options?: RequestInit): Promise<getUserBuyOrders2Response> => {
  
  return customInstance<getUserBuyOrders2Response>(getGetUserBuyOrders2Url(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserBuyOrders2QueryKey = () => {
    return [
    `/api/users-orders/buy`
    ] as const;
    }

    
export const getGetUserBuyOrders2QueryOptions = <TData = Awaited<ReturnType<typeof getUserBuyOrders2>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserBuyOrders2QueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBuyOrders2>>> = ({ signal }) => getUserBuyOrders2({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserBuyOrders2QueryResult = NonNullable<Awaited<ReturnType<typeof getUserBuyOrders2>>>
export type GetUserBuyOrders2QueryError = unknown


export function useGetUserBuyOrders2<TData = Awaited<ReturnType<typeof getUserBuyOrders2>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBuyOrders2>>,
          TError,
          Awaited<ReturnType<typeof getUserBuyOrders2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBuyOrders2<TData = Awaited<ReturnType<typeof getUserBuyOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBuyOrders2>>,
          TError,
          Awaited<ReturnType<typeof getUserBuyOrders2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBuyOrders2<TData = Awaited<ReturnType<typeof getUserBuyOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserBuyOrders2<TData = Awaited<ReturnType<typeof getUserBuyOrders2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBuyOrders2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserBuyOrders2QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type sellOrderBookResponse200 = {
  data: Blob
  status: 200
}
    
export type sellOrderBookResponseSuccess = (sellOrderBookResponse200) & {
  headers: Headers;
};
;

export type sellOrderBookResponse = (sellOrderBookResponseSuccess)

export const getSellOrderBookUrl = (token: string,) => {


  

  return `/api/users-orders/book/${token}/sell`
}

export const sellOrderBook = async (token: string, options?: RequestInit): Promise<sellOrderBookResponse> => {
  
  return customInstance<sellOrderBookResponse>(getSellOrderBookUrl(token),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSellOrderBookQueryKey = (token: string,) => {
    return [
    `/api/users-orders/book/${token}/sell`
    ] as const;
    }

    
export const getSellOrderBookQueryOptions = <TData = Awaited<ReturnType<typeof sellOrderBook>>, TError = unknown>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sellOrderBook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSellOrderBookQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sellOrderBook>>> = ({ signal }) => sellOrderBook(token, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sellOrderBook>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SellOrderBookQueryResult = NonNullable<Awaited<ReturnType<typeof sellOrderBook>>>
export type SellOrderBookQueryError = unknown


export function useSellOrderBook<TData = Awaited<ReturnType<typeof sellOrderBook>>, TError = unknown>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sellOrderBook>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sellOrderBook>>,
          TError,
          Awaited<ReturnType<typeof sellOrderBook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSellOrderBook<TData = Awaited<ReturnType<typeof sellOrderBook>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sellOrderBook>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sellOrderBook>>,
          TError,
          Awaited<ReturnType<typeof sellOrderBook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSellOrderBook<TData = Awaited<ReturnType<typeof sellOrderBook>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sellOrderBook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSellOrderBook<TData = Awaited<ReturnType<typeof sellOrderBook>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sellOrderBook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSellOrderBookQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type buyOrderBookResponse200 = {
  data: Blob
  status: 200
}
    
export type buyOrderBookResponseSuccess = (buyOrderBookResponse200) & {
  headers: Headers;
};
;

export type buyOrderBookResponse = (buyOrderBookResponseSuccess)

export const getBuyOrderBookUrl = (token: string,) => {


  

  return `/api/users-orders/book/${token}/buy`
}

export const buyOrderBook = async (token: string, options?: RequestInit): Promise<buyOrderBookResponse> => {
  
  return customInstance<buyOrderBookResponse>(getBuyOrderBookUrl(token),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getBuyOrderBookQueryKey = (token: string,) => {
    return [
    `/api/users-orders/book/${token}/buy`
    ] as const;
    }

    
export const getBuyOrderBookQueryOptions = <TData = Awaited<ReturnType<typeof buyOrderBook>>, TError = unknown>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof buyOrderBook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBuyOrderBookQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof buyOrderBook>>> = ({ signal }) => buyOrderBook(token, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof buyOrderBook>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BuyOrderBookQueryResult = NonNullable<Awaited<ReturnType<typeof buyOrderBook>>>
export type BuyOrderBookQueryError = unknown


export function useBuyOrderBook<TData = Awaited<ReturnType<typeof buyOrderBook>>, TError = unknown>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof buyOrderBook>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buyOrderBook>>,
          TError,
          Awaited<ReturnType<typeof buyOrderBook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBuyOrderBook<TData = Awaited<ReturnType<typeof buyOrderBook>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof buyOrderBook>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buyOrderBook>>,
          TError,
          Awaited<ReturnType<typeof buyOrderBook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBuyOrderBook<TData = Awaited<ReturnType<typeof buyOrderBook>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof buyOrderBook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBuyOrderBook<TData = Awaited<ReturnType<typeof buyOrderBook>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof buyOrderBook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBuyOrderBookQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type cancelOrderResponse200 = {
  data: Blob
  status: 200
}
    
export type cancelOrderResponseSuccess = (cancelOrderResponse200) & {
  headers: Headers;
};
;

export type cancelOrderResponse = (cancelOrderResponseSuccess)

export const getCancelOrderUrl = (orderId: number,) => {


  

  return `/api/users-orders/limit/${orderId}`
}

export const cancelOrder = async (orderId: number, options?: RequestInit): Promise<cancelOrderResponse> => {
  
  return customInstance<cancelOrderResponse>(getCancelOrderUrl(orderId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getCancelOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{orderId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{orderId: number}, TContext> => {

const mutationKey = ['cancelOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelOrder>>, {orderId: number}> = (props) => {
          const {orderId} = props ?? {};

          return  cancelOrder(orderId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CancelOrderMutationResult = NonNullable<Awaited<ReturnType<typeof cancelOrder>>>
    
    export type CancelOrderMutationError = unknown

    export const useCancelOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelOrder>>, TError,{orderId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cancelOrder>>,
        TError,
        {orderId: number},
        TContext
      > => {
      return useMutation(getCancelOrderMutationOptions(options), queryClient);
    }
